### ISSUE TITLE
online demo?

### ISSUE THREAD

**Issue by andzi** [PierreCapo/treeviz#1]
It would be nice to put link to online demo for "first look"

**Comment by PierreCapo** [comment]
Hey ! Good idea, I will do it as soon as possible. Any tool you would recommand for doing it ?

**Comment by andzi** [comment]
I don't get what you mean by "tool"? it could be github page with some data & tree structures (see samples at https://github.com/d3/d3/wiki/gallery)

**Comment by PierreCapo** [comment]
Added a codepen which shows a demo of the library and Readme updated:
https://codepen.io/anon/pen/BPNvYL

**Comment by andzi** [comment]
Niccce, but not the end:

- no title, what can I say ;-/
- terrible look - not fits to window, if no 'autofit' then, probably, useless. I see 'nodesetings' but what about whole canvas (window for tree), who is responsible for 'resposive design'?
- scratching my head, can't find how (where) to change orientation
