### ISSUE TITLE
Not able to create a below flow . Any suggessions

### ISSUE THREAD

**Issue by ranjith29h** [PierreCapo/treeviz#17]
![Untitled Diagram](https://user-images.githubusercontent.com/12975992/55862790-cd5a9b00-5b96-11e9-9ce3-d8fa310479fa.png)

**Comment by PierreCapo** [comment]
Hello ! What you are trying to represent is not a **tree** , you are trying to represent a **graph**. 

Although they seem similar visually, trees and graphs have got really different mathematical properties which leads to difference when computing layouts. For instance trees display a hierarchy between nodes (Father to children) whereas graphs are just nodes connected to each other. 

To sum up, Treeviz is here to display trees, if you want to display graphs I advice you to look for libraries based on d3 which displays graphs to suit your need
