### ISSUE TITLE
linkShapre orthogonal problem on firefox

### ISSUE THREAD

**Issue by phulecse2420** [PierreCapo/treeviz#21]
Hi Pierre,

I am using treeviz version 1.3.3 on newest Firefox. The linkShapre orthogonal works are incorrect on Firefox.

Your example in this page meet problem like me.
https://pierrecapo.github.io/treeviz-react/?path=/story/storybook--treeviz

![Annotation 2019-07-31 134600](https://user-images.githubusercontent.com/8969253/62189457-314cdd80-b399-11e9-952a-ff94444d741b.png)

The linkShape quadraticBeziers is working OK.
Please help to fix this.

Another ask that can you support new style of linkShape like below.
![Annotation 2019-07-31 135156](https://user-images.githubusercontent.com/8969253/62189811-2a729a80-b39a-11e9-8707-98bf45cbe053.png)

 Always happy to hear from you.
Thanks,
Phu Le

**Comment by PierreCapo** [comment]
Hello @phulecse2420, sorry for responding late, I didn't see your issue.
1. About the bug on firefox, I don't really know what's happening, I'm going to investigate it.
2. About the shape you want to display, it shouldn't be complicated to do, I'll probably going to release a version before the end of the week with the path you've requested.
Thanks for the report, I'll ping you when it's ready :)

**Comment by phulecse2420** [comment]
That's sound great. Thank you very much.

**Comment by PierreCapo** [comment]
@phulecse2420 
Does this shape satisfy your need ?

![image](https://user-images.githubusercontent.com/26744253/62392060-b6d1b880-b566-11e9-9eb9-38990048ee6e.png)

Just to be sure to satisfy you'll be happy with this new shape. Don't hesitate to ask for some changes if you'd like something different :)

**Comment by phulecse2420** [comment]
Thank you very much. It met my requirements. Good job!

**Comment by nguyenkatd** [comment]
Many thanks to you. I just voted star for you. ;))

**Comment by PierreCapo** [comment]
@phulecse2420 I've just released a new version of treeviz (2.1.0) with this new shape. To use it, you can do:`linkShape: "curve"`. You can also check the [storybook](https://pierrecapo.github.io/treeviz-react/?path=/story/storybook--treeviz) to see how it looks.

@nguyenkatd Thanks for the star, that is really appreciated

**Comment by nguyenkatd** [comment]
Hi PierreCapo,
   We got problem with your new release 2.0.1 .
   My datas below have worked good on version 1.3.3.

![image](https://user-images.githubusercontent.com/33349514/62439054-83fd0f80-b774-11e9-9090-172b1d2512e2.png)

  And here is my config for treeviz:
var myTree = Treeviz.create({
	    htmlId: "tree",
	    nodeField: "uid",
	    hasFlatData: true,
	    relationnalField: "parent",
	    nodeWidth: 120,
	    nodeHeight: 140,
	    renderNode: (nodeData) => drawNode(nodeData),
	    linkWidth: nodeData => 1,
	    linkColor: nodeData => "#292c2e",
	    linkShape: "curve"
	});
	myTree.refresh(mlmTree);

And we got :
![image](https://user-images.githubusercontent.com/33349514/62439761-477ee300-b777-11e9-9638-bfe56272cd2b.png)

Please help me to fix this. And nodeTemplate(as renderNode with 2.0.1) not working also.

Thank you and hope the best to you. !

**Comment by PierreCapo** [comment]
Oops that's my bad, I forgot to edit properly the README of the project. In v2, the `nodeField` property has been renamed to `idKey` (because I've thought it was more self explaining). 
Can you try with that ?

The render node prop uses now the d3 "standard" parameter in order to access the maximum amount of information per node. Can you try: `renderNode: (node) => drawNode(node.data)`

**Comment by nguyenkatd** [comment]
Yay. Now working. Thanks @PierreCapo 

![image](https://user-images.githubusercontent.com/33349514/62453011-95a5dd80-b79b-11e9-9195-ef15d006a721.png)

And also, can you update your newest README. ^__^

**Comment by PierreCapo** [comment]
Happy it's working now, sorry for the inconvenience. The README has been updated.
Thanks for the report
