### ISSUE TITLE
Zoom on mouse location

### ISSUE THREAD

**Issue by seba1342** [PierreCapo/treeviz#23]
Hi Pierre,

Just wanted to flag something I have noticed. When using your Storybook example to zoom in, the zoom functionality works as expected on the x-axis but on the y-axis it seems to zoom downwards of the mouse position.

This in a horizontal layout isn't the largest of issues, however I use the treeviz in a vertical layout, which means while it maintains a correct y-axis position, the zoom seems to veer right on the x-axis. 

Just wondering if there is a fix that you can see for this?

Thanks in advance,

Seb

**Comment by PierreCapo** [comment]
Hello seba!
I'm going to try to look at it today.
Thanks for the report :)

**Comment by seba1342** [comment]
Thanks heaps

**Comment by PierreCapo** [comment]
Hello @seba1342 quick update on your issue:
I've found the bug, but it's not that easy to fix, so I'll probably publish a fix in the incoming week only.

**Comment by seba1342** [comment]
Amazing! Thankyou @PierreCapo, looking forward to the fix 😍

**Comment by PierreCapo** [comment]
Hello @seba1342 , sorry for the delay!

I've released a new version of treeviz with the zoom fix. You can check in the [storybook](https://pierrecapo.github.io/treeviz-react/?path=/story/storybook--treeviz) that the zoom should work properly now, but feel free to reopen the issue if you see something wrong.

I hope your family tree is going well ;)
Regards

Pierre

**Comment by seba1342** [comment]
Hey thanks for working on this @PierreCapo , really appreciate it and it works super nicely in the storybook. I just updated the package now and I get the following error in my console when I run it, any ideas why?
```Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.```

**Comment by PierreCapo** [comment]
Did you upgrade from version 1.3.x to 2.1.1? Take care a lot of properties in the config file have been renamed, for better self-explaining variables. Particularly `htmlID` has been renamed to `htmlId` to follow web standards, and I think this is what's causing your issue.

**Comment by seba1342** [comment]
Woops, should've taken a closer look at the updated README, thank you @PierreCapo all is restored to its former glory!
Will share the final product with you when it is complete on twitter! Thanks again for your responses and fixes <3
