### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.

### ISSUE THREAD

**Issue by Laferu** [PierreCapo/treeviz#24]

**Comment by PierreCapo** [comment]
Hello @Laferu , thanks for the report, can you give me a way to reproduce your bug please ? Like a repository link or something like that.
Thanks in advance

**Comment by PierreCapo** [comment]
Basically what I suspect from the error, is that you didn't pass the `htmlId` property to treeviz (case sensitive), and so the querySelector command crashes and is not able to find the html element to draw the treeviz component.

**Comment by Laferu** [comment]
I used the example from your own repository and this error happens.

**Comment by PierreCapo** [comment]
Oh, thanks for the report ;)
Fixed.
