### ISSUE TITLE
Dynamic Node Height

### ISSUE THREAD

**Issue by saadrawasia** [PierreCapo/treeviz#25]
There must be feature to have a dynamic node height, based on the content of the node, instead of having just pixel based node height.
Thanks

**Comment by PierreCapo** [comment]
Hello @saadrawasia ! Thanks for the issue. I will investigate that. 
Quick question to be sure we are on the same spot : do you want to have a dynamic height per node ? That would lead to having nodes with different height in the same tree graph.

Also if possible can you share a minimal reproduction of your code so I can work it and be sure I've fixed what you want ?

**Comment by saadrawasia** [comment]
> Hello @saadrawasia ! Thanks for the issue. I will investigate that.
> Quick question to be sure we are on the same spot : do you want to have a dynamic height per node ? That would lead to having nodes with different height in the same tree graph.
> 
> Also if possible can you share a minimal reproduction of your code so I can work it and be sure I've fixed what you want ?

Yes i want dynamic height per node in a same tree graph like height should be set based on the content of the node, instead of providing height for each node.

**Comment by PierreCapo** [comment]
According to https://github.com/d3/d3-hierarchy/issues/93 it seems that I will need to rely on moving from d3-hierarchy to [d3-flextree](https://github.com/klortho/d3-flextree) to achieve what you want. I'll keep you updated

**Comment by PierreCapo** [comment]
@saadrawasia from what I see from d3-flextree, it needs to know in advance (when you configure the tree) what are the size you want to have for each node. There is no solution to have nodes where the size is evaluated automatically based on the content of the node.
