### ISSUE TITLE
Separate options for hasPanAndZoom?

### ISSUE THREAD

**Issue by LiddleDev** [PierreCapo/treeviz#26]
Would it be possible to split this out into two options? For example if I wanted to enable panning but disable zooming I could pass

hasPan: true,
hasZoom: false,

Thanks

**Comment by PierreCapo** [comment]
Hello @LiddleDev
I gonna look at it, it shouldn't be that hard to do. Sadly it will be a breaking change though, so it will need a version 3.

**Comment by LiddleDev** [comment]
Perfect thank you! Alternatively you could add in those two new options which override the original hasPanAndZoom? Either way, thanks for the quick response :)

**Comment by PierreCapo** [comment]
Oh yeah, you are right I'll do that. I'll try to look at it this week-end ;)

**Comment by PierreCapo** [comment]
Hello @LiddleDev , sorry for the delay. Your requested features has been merged and is available on treeviz `2.2.0`. Enjoy !
