### ISSUE TITLE
linkColor doesn't re-trigger on update

### ISSUE THREAD

**Issue by nicolasmgaray** [PierreCapo/treeviz#28]
If you have a linkColor that depends on some property of the node itself, and the node updates, the linkColor won't update acording to it:

![image](https://user-images.githubusercontent.com/29661506/74531268-f2ccd980-4f0a-11ea-92c8-7136b1d3efe1.png)

In this case, the node and the link started in red color, after an update a property of the node changed and the node background changed to green (but not the link).

I found that this is because the links only draw 1 time. (probable because performance)

Maybe its posible to configurate if linkColor is executed several times or no ?

**Comment by PierreCapo** [comment]
Hello @nicolasmgaray 
Thanks for using treeviz!

I've just published a new version (2.2.1) which rerenders link color on updates. Performance should be fine, I just didn't have the usecase when I built the library and I didn't think it could be useful to someone.
Have a good day 😀

**Comment by nicolasmgaray** [comment]
Thanks a lot man!!! You really helped me with this! 
Love your module, its really simple, flexible, and easy to use!!

Great work!!!
