### ISSUE TITLE
make tree size to viewport

### ISSUE THREAD

**Issue by ypeskin** [PierreCapo/treeviz#3]
Hello,
is it possible to have the tree to display at the correct zoom to include the entire tree?

**Comment by PierreCapo** [comment]
Hello ! Nice proposition, it's probably possible to do it yes. I'll look at it later in the day when I got time, I'll stay you in touch

**Comment by PierreCapo** [comment]
@ypeskin I have added a`nodeDepthDistance`key to configure the tree. When set to `"auto"` it tries to fit the viewport along the main axis.
Can you try the new version and tell me if it's ok for your use case ?

**Comment by ypeskin** [comment]
Pierre,I tried the auto option and see attachment for what it looks like.Thanks,
-- Yury Peskin ypeskin@yahoo.com 

    On Saturday, February 9, 2019, 6:10:41 AM CST, PierreCapo <notifications@github.com> wrote:  
 
 
@ypeskin I have added anodeDepthDistancekey to configure the tree. When set to "auto" it tries to fit the viewport along the main axis.
Can you try the new version and tell me if it's ok for your use case ?

**Comment by PierreCapo** [comment]
@ypeskin can I consider this issue as solved so ?

**Comment by ypeskin** [comment]
Pierre,I don't think it's working as intended. With nodeDepthDistance set to "auto"  I get this:

as you can see in the picture, nodes are scrunched together plus there's another level of nodes off the bottom of screen, you can barely see the links.Thank you,
-- Yury Peskin ypeskin@yahoo.com 

    On Tuesday, February 19, 2019, 10:17:38 AM CST, PierreCapo <notifications@github.com> wrote:  
 
 
@ypeskin can I consider this issue as solved so ?

**Comment by PierreCapo** [comment]
@ypeskin it seems that you are replying by email, and so I do not see the attachments. Can you reply directly on Github and join the pictures please ?

**Comment by ypeskin** [comment]
Sorry, Here's the attachment.
![image](https://user-images.githubusercontent.com/1278739/53032031-a3f17e80-3433-11e9-8159-1739905b0dc0.png)
