### ISSUE TITLE
Issue with importing when using NextJS

### ISSUE THREAD

**Issue by PeterBowater** [PierreCapo/treeviz#34]
Hi again, sorry to bother you twice in one day...

When I refresh the page, or I am building my nextJS app, I'm getting this error come up :

<img width="1061" alt="Screenshot 2020-04-06 at 16 44 57" src="https://user-images.githubusercontent.com/807991/78577541-20a50f00-7826-11ea-9725-349d5dbdeea4.png">

I'm unsure why this is happening, but suspect it may be something to do with the version of javascript that the typescript is being compiled into, causing the import to fall over.

I'm using the demo code almost unaltered for this, so I don't think it is something I have done, but happy to be corrected.

Hope you can point me in the right direction?

Thanks!

Peter

**Comment by PierreCapo** [comment]
Hello Peter,
No problem, don't worry.

I have never used nextjs, so for this one I think I'll need that you create a repository with the reproducible code so I can debug what exactly is going wrong.

Is this bug only happening with `treeviz-react` ? Can you confirm it's working well with other libraries ?

**Comment by PeterBowater** [comment]
Thanks Pierre,

I had another bodge at this this morning, again after updating packages.

It produced a different error this time, saying window was not defined,. which in Next is not an uncommon thing due to the SSR.

I moved treeviz outside of SSR, and it is now reloading the page correctly when refreshing.

Given the different error, I wonder the other error was falsely presenting, sending me down a rabbit hole. No real way to check now I guess without rolling everything back, but I am happy that this once is fixed as well.

Thanks again for your help! 

Peter.
