### ISSUE TITLE
Refresh issue. TypeError: Cannot read property 'x0' of undefined

### ISSUE THREAD

**Issue by Pronink** [PierreCapo/treeviz#36]
Hello !
I made a function when you click into one node, in one copy of original data, I delete all its childrens, making a "grouping feature" (gif at bottom). Then I call `refresh(newData)` to update the tree.
But sometimes the nodes and lines which connects that nodes disapears:
![image](https://user-images.githubusercontent.com/17512287/79312513-4a81c400-7eff-11ea-96c5-dc0a6384aa83.png)
In the console, each refresh I received this: (**index.js** is the compiled treeviz library)
```
angular.js:14642 TypeError: Cannot read property 'x0' of undefined
    at SVGGElement.<anonymous> (index.js:1)
    at SVGGElement.<anonymous> (index.js:1)
    at xn.each (index.js:1)
    at ut (index.js:1)
    at xn.attr (index.js:1)
    at Object.n.drawNodeExit (index.js:1)
    at index.js:1
    at Object.refresh (index.js:1)
    at Controller.renderTree (Controller.ts:278)
    at eval (Controller.ts:142)
    at eval (angular.js:17000)
    at m.$digest (angular.js:18182)
    at m.$apply (angular.js:18480)
    at l (angular.js:12501)
    at XMLHttpRequest.s.onload (angular.js:12655) "Possibly unhandled rejection: {}"
```
If with the same current data I do:
```
this.treeChart.clean();
this.treeChart = null;
```
... and then re-render with the same data that before, it fixes:
![image](https://user-images.githubusercontent.com/17512287/79312658-80bf4380-7eff-11ea-88f4-38c8ad02dc0d.png)
So I think there must be an error in the refresh function. Can I get a "not minified" version of compiled treeviz to investigate it better?
Here one gif of grouping feature (and a minor transition glitch):
![ezgif-2-2f62c045276f](https://user-images.githubusercontent.com/17512287/79312156-c3cce700-7efe-11ea-91aa-544f00fe2378.gif)
Object example:
```json
{
id: 90100000,
father: 1000100000,
...
},
```
Thanks a lot !!
Regards

**Comment by PierreCapo** [comment]
Hello @Pronink ,
Multiple things for you:

- if you want to investigate the source code, it's there: https://github.com/PierreCapo/treeviz/tree/master/packages/treeviz/ you need to compile it using typescript compiler `tsc --p ./tsconfig.json`

- My first guess seing the issue : `x0` is about the parent node so this is where we should look at.

- Finally, I'd really need a reproduction, because I'm unable to reproduce the bug on the [storybook](https://pierrecapo.github.io/treeviz-react/?path=/story/storybook--treeviz). If you could set up a repository and give me the link that would be great. I'm a bit busy this week but I could have a look this week-end.

Have a good day!

**Comment by Pronink** [comment]
I could reproduce it in storybook: [VIDEO](https://i.gyazo.com/e709c181430b00039333cfc98cf967c7.mp4)
I'm using Google Chrome Versión 80.0.3987.163 (Build oficial) (64 bits)
```
EDIT
In Chrome Versión 81.0.4044.92 (Build oficial) (64 bits) I also have the same problem.
```
In firefox I get the same issue

Chrome error:
![image](https://user-images.githubusercontent.com/17512287/79327071-241a5380-7f14-11ea-8ce2-c16bfd3d94b8.png)

Firefox error:
![image](https://user-images.githubusercontent.com/17512287/79326991-0351fe00-7f14-11ea-885e-9f349497f381.png)

Apparently it seems the same error that I am having, although in my case the nodes do not disappear, they break. Another example:
![image](https://user-images.githubusercontent.com/17512287/79327443-bf132d80-7f14-11ea-89d8-f785d1b1d8c5.png)
![image](https://user-images.githubusercontent.com/17512287/79327508-e10cb000-7f14-11ea-9f42-b689bc63cc49.png)

I will try to make a workaround using try catch: if refresh() fails, I'll do full repaint:
```javascript
this.treeChart.clean();
this.treeChart = treeviz.create(...);
this.treeChart.refresh(data);
```
Thanks for the quickness !
If I can this weekend I will make a reproducible code example. (Although it can be reproduced in the storybook)
Have a good day !!

**Comment by Pronink** [comment]
Good morning !
Could you reproduce it last weekend?
I could reproduce it your storybook: [VIDEO](https://i.gyazo.com/e709c181430b00039333cfc98cf967c7.mp4)
If you need anything else tell me ;-)
Have a good day !!

**Comment by PierreCapo** [comment]
Hello @Pronink ,
Sorry I got really busy. I hope to fix it soon but can't promise anything since I got a lot of work 🙏. I'll ping you when I do a release.

Thanks for the video, indeed I can reproduce the bug

**Comment by Pronink** [comment]
Okey, no problem 😉
I did a workaround (try-catch 👹) like I told you so don't rush.
Thank you for making this great library and have a good day !!
