### ISSUE TITLE
Doc/readme using in correct parameter for flat data

### ISSUE THREAD

**Issue by PeterBowater** [PierreCapo/treeviz#37]
Hi Pierre,

Still working with this, it's great!

Had a bit of a wrangle with flat data, and found that the configuration table are correct in the use of 'hasFlatData=', but the two examples you give just above uses 'flatData='

Hope that helps! :)

Peter.

**Comment by PierreCapo** [comment]
Wow @PeterBowater  nice catch! I need to fix that, thank you 👍

**Comment by PierreCapo** [comment]
Thanks again for the report @PeterBowater 
Fixed in https://github.com/PierreCapo/treeviz/commit/6778bb2efe2d9a94c5cc687272069d082a03a981

**Comment by PeterBowater** [comment]
Thanks Pierre! :)
