### ISSUE TITLE
Standalone library?

### ISSUE THREAD

**Issue by infinity77** [PierreCapo/treeviz#52]
I am having a phenomenally hard time to get npm to work behind a corporate firewall, no matter what I do with the npm proxy settings. Is there any chance someone could make a standalone **Javascript** library out of this beautiful tree renderer?

Thank you in advance.

Andrea.

**Comment by PierreCapo** [comment]
Hello @infinity77 if i understand what you want, you'd like to have a way to inject treeviz with something like 
```
<script src="http://.../treeviz"><script>
```
is that what you want ?

If that is the case, you can clone the project, and generate a dist file for treeviz and ship it with your website.
If for whatever reason this is not possible and you need that the client fetches treeviz from a CDN,  we need to host the treeviz dist file on a CDN. I assume it's not that complicated to set up, but I've never done it and I'd need probably some help.

Thanks for the kind words by the way 😀

**Comment by infinity77** [comment]
Hi Pierre,

this is exactly what I am trying to do, with little success. I can't use npm so I can't easily get typescript, to convert the index.ts to index.js or something that the browser will understand. I don't need a client that fetches the library, just something that works standalone embedding it like you wrote above.

**Comment by PierreCapo** [comment]
Okay, I used to commit the dist file but at some point I gitignored it because I didn't find any usecase, seems like there is one actually 😅

**Comment by PierreCapo** [comment]
Done, should be available in : https://github.com/PierreCapo/treeviz/tree/master/packages/treeviz/dist

**Comment by infinity77** [comment]
Thank you! That was super fast and super kind of you!

**Comment by PierreCapo** [comment]
Great! Glad to help, have a good day 😀
