### ISSUE TITLE
treeviz and ie

### ISSUE THREAD

**Issue by ypeskin** [PierreCapo/treeviz#6]
Hi Pierre,
It's me again. 
One of the requirements to display the diagram is IE compatibility. The reason IE is important is because the database that we are using uses IE to display reports, so it's kind of mandatory to have IE compatibility. Well, I hate IE and was using chrome to develop. But now, we're in a testing phase, and IE compatibility requirement is starting to bite me. I am getting the following errors while running treeviz in IE:
 SCRIPT1002: Syntax error at index.js (1, 1192). 
Since the index.js is minified there isn't a lot I can do on my end.
I believe it happens when parsing the config specifically when parsing the following line, because the second error is SCRIPT1002: Syntax error at my_html_file.js at this line:
      nodeColor: (nodeData) => "#ffffff"
It works fine on Edge, it's just IE that's causing the issue.
Any help would be appreciated.

**Comment by PierreCapo** [comment]
Hello Yury,
Can you tell me the version of Internet Explorer required to support ? If it's IE11 I'm pretty confident to make it work by today. Otherwise it might take a bit longer to set up.

**Comment by ypeskin** [comment]
Hello Pierre,
Yes, IE 11 support would be good enough. 
On Edge, when you zoom in/out the node looks like it's cutoff.
Here's what it looks like, prior to zoom:
![image](https://user-images.githubusercontent.com/1278739/53172209-62cfaa80-35aa-11e9-98a2-9e5c5db6a95d.png)
And after zoom:
![image](https://user-images.githubusercontent.com/1278739/53172255-7d098880-35aa-11e9-8167-f325e415f044.png)

I'm not sure if you want me to start another issue for this or not.
Let me know,
Yury

**Comment by PierreCapo** [comment]
Hey Yury, fine, I'll try to release a version which supports IE11 by this night. If you can open a new issue for the Microsoft Edge bug that would be cool :) Thanks

**Comment by PierreCapo** [comment]
Support for IE11 added with #9 @ypeskin I close this issue for now, feel free to reopen it if you have any issue running it again on internet explorer

**Comment by PierreCapo** [comment]
@ypeskin oh and also don't forget to change the arrow functions into function with the `function`keyword when you use the libray inside your `<script>` tag

**Comment by ypeskin** [comment]
Pierre,
What do you mean by "don't forget to change the arrow functions into function with the function keyword"?

**Comment by ypeskin** [comment]
Oh, Never mind. I found a tutorial. Thank you.

**Comment by ypeskin** [comment]
Hi Pierro,
I get this error when testing in IE11:
 Unable to get property 'setProperty' of undefined or null reference. FYI, I have changed the arrow functions to regular functions. Here's the updated code:
 $(function () {
    $(window).load(function () {
      $("#divTree").width($(window).width());
    });
    $(window).resize(function () {
      $("#divTree").width($(window).width());
    });
    const treeConfig = {
      htmlID: "divTree",
      nodeField: "MatlItem",
      flatData: false,
      relationnalField: "Children",
      zoomBehavior: true,
      nodeSpacerPercentage: 1.20,
      nodeWidth: 125,
      nodeHeight: 80,
      nodeColor: function (nodeData) { return "#ffffff" },
      horizontalLayout: false,
      linkColor: function (nodeData) { return "#000000" },
      linkShape: "orthogonal",
      linkWidth: function (nodeData) { return 3 },
      depthDistance: 5,
      //    nodeDepthDistance: "auto",
      nodeTemplate: function (nodeData) { return "<div style='height:75px;width:120px;display:flex;flex-direction:column;justify-content:center;align-items:center;border:2px solid black;'><div><b>" + nodeData.MatlItem + "</b></div><div style='border:1px solid black;width:110px;text-align:center; vertical-align: middle;'> Lead Time: " + nodeData.LeadTime + "</div></div>" }
    }

    var myTree = Treeviz.create(treeConfig); // create a tree based on the config

    $("#submit_button").click(function() {
      var item = $("#txtItem").val();
      $("divLoading").show();
      if (item) {
        $.ajax({
          cache: false,
          type: 'Get',
          url: '@Url.Action("GetBom")',
          data: { itm: item },
          success: function (data) {
            $("#divLoading").hide();
            if (data.Success == "OK") {
              myTree.clean(); // delete the old tree
              myTree = Treeviz.create(treeConfig); // configure a new tree with the previous same configuration
              myTree.refresh(data); // refresh new tree
            }
            else {
              alert(data.Message);
            }
          }
        });
      }
    });
  });
