### ISSUE TITLE
treeviz issue with Edge

### ISSUE THREAD

**Issue by ypeskin** [PierreCapo/treeviz#7]
On Edge, when you zoom in/out the node looks like it's cutoff.
Here's what it looks like, prior to zoom:
![image](https://user-images.githubusercontent.com/1278739/53172209-62cfaa80-35aa-11e9-98a2-9e5c5db6a95d.png)
And after zoom:
![image](https://user-images.githubusercontent.com/1278739/53172255-7d098880-35aa-11e9-8167-f325e415f044.png)
Thanks,
Yury

**Comment by PierreCapo** [comment]
@ypeskin could you provide me the code you used for the `nodeTemplate` field please ? Also does it happen on Firefox or Chrome ?

**Comment by ypeskin** [comment]
Here's the entire html file:
@model IEnumerable<EF6SytelineData.Model.SIBillOfMaterialsWithMfgLeadTimesModel>

@{
  ViewBag.Title = "BillOfMaterialsDisplay";
}
<div id="criteria">
  <table class="dataTable">
    <tr>
      <td class="firstcolumn">
        Item
      </td>
      <td>
        <input type="text" id="txtItem" />
      </td>
    </tr>
    <tr>
      <td class="firstcolumn"></td>
      <td>
        <input type="button" class="k-button" value="Update" onclick="getBom()" />
      </td>
    </tr>
  </table>
</div>

<hr />

<div id="divLoading" style="display:none;">
  <img src="http://siww/images/loading.gif" alt="loading" />
</div>

<div id="divDetails" style="width: auto; height:auto; margin:0; padding:auto, 0;">
  <div id="divTree" style="margin:0; padding:0; width:1000px; height:1000px;"></div>
</div>
<script src="~/Scripts/treeviz/1.2.0/index.js"></script>
<script>
  // auto,0,auto,0
  $(function () {
    $(window).load(function () {
      $("#divTree").width($(window).width());
    });
    $(window).resize(function () {
      $("#divTree").width($(window).width());
    });
  });

  const treeConfig = {
    htmlID: "divTree",
    nodeField: "MatlItem",
    flatData: false,
    relationnalField: "Children",
    zoomBehavior: true,
    nodeSpacerPercentage: 1.20,
    nodeWidth: 125,
    nodeHeight: 80,
    nodeColor: (nodeData) =>"#ffffff",
    horizontalLayout: false,
    linkColor: (nodeData) => "#000000",
    linkShape: "orthogonal",
    linkWidth: (nodeDatat) => 3,
    depthDistance: 5,
//    nodeDepthDistance: "auto",
    nodeTemplate: (nodeData) => "<div style='height:75px;width:120px;display:flex;flex-direction:column;justify-content:center;align-items:center;border:2px solid black;'><div><b>" + nodeData.MatlItem + "</b></div><div style='border:1px solid black;width:110px;text-align:center; vertical-align: middle;'> Lead Time: " + nodeData.LeadTime + "</div></div>"
  }

  let myTree = Treeviz.create(treeConfig); // create a tree based on the config

  function getBom() {
    var item = $("#txtItem").val();
    $("divLoading").show();
    if (item) {
      $.ajax({
        cache: false,
        type: 'Get',
        url: '@Url.Action("GetBom")',
        data: { itm: item },
        success: function (data) {
          $("#divLoading").hide();
          if (data.Success == "OK") {
            myTree.clean(); // delete the old tree
            myTree = Treeviz.create(treeConfig); // configure a new tree with the previous same configuration
            myTree.refresh(data); // refresh new tree
          }
          else {
            alert(data.Message);
          }
        }
      });
    }
  }
</script>

This only occurs in IE.

**Comment by PierreCapo** [comment]
it occurs with Edge, not IE right ?

**Comment by ypeskin** [comment]
I haven’t been able to test with IE due to the syntax error I was getting.

Yury Peskin
IT ERP Developer
Standard Iron
524 Pine Street
Monticello, MN. 55362
Yury.Peskin@std-iron.com

**Comment by ypeskin** [comment]
Pierre,
I was testing your code and I don't think you merged clean-method branch into the master yet. Because, I keep getting an error: TypeError: myTree.clean is not a function
    at Object.success (BillOfMaterialsDisplay:123)
    at i (jquery-1.12.4.min.js:2)

**Comment by PierreCapo** [comment]
Yeah you are right, I forget to merge it. It should work now

**Comment by ypeskin** [comment]
Great, thanks. I'll try it again tomorrow.

**Comment by PierreCapo** [comment]
Closing since Edge is going to move soon to Chromium
