### ISSUE TITLE
Zoom and Pan has not effect

### ISSUE THREAD

**Issue by sahilsujeet1** [PierreCapo/treeviz#86]
I am using treeviz with an Angular application using typescript. The tree is created without a problem. I am setting hasZoom and hasPan to false but unfortunately it does not show any effect. The tree gets zoomed on scroll anyway and pan still works.

**Comment by moralju** [comment]
was this fixed?

**Comment by sahilsujeet1** [comment]
I am not sure about that. My internship has been over and I am not using treeviz anymore.
